apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-watcher
  template:
    metadata:
      labels:
        app: file-watcher
    spec:
      containers:
        - name: file-watcher
          image: file_watcher:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "ingest_watcher.py"]
          env:
            - name: API_URL
              value: "http://api-server:8001/db/add"
          volumeMounts:
            - name: papers-volume
              mountPath: /app/papers
      volumes:
        - name: papers-volume
          hostPath:
            # This path is on the Ubuntu VM that runs the Kubernetes node.
            path: /opt/papers
            type: DirectoryOrCreate
